[package]
name = "pyrope"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyrope_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "chrono"] }
chrono = "0.4"

[package.metadata.maturin]
name = "pyrope_native"
